name: ets2_environments
description: "Uma forma fácil de separar ambientes para rodar mods diferentes em perfis diferentes no Euro Truck Simulator 2 [windows]"
publish_to: 'none'
version: 0.0.4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.0
  filepicker_windows: ^2.0.11
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.1.0
  get_it: ^7.6.6
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sxc/
    - assets/sxc/addons/
    - assets/sxc/addons/packer/
    - assets/sxc/addons/packer/img/
    - assets/sxc/addons/pathfinder/
    - assets/sii_decrypt/


